import { EntryFragment } from 'autogenerated/graphql-types'
import * as React from 'react'
import { foldNullables } from 'src/utils/functional'
import { ret } from 'src/utils/pointfree'
import Entry from './entry'

type Props = {
  entries: EntryFragment[]
}

export const Entries = ({ entries }: Props) => <>
  {entries.map(
    ({ body, slug, frontmatter }, index) => foldNullables(
      { title: frontmatter?.title, tags: frontmatter?.tags },
      ret(null),
      ({ title, tags }) =>
        <Entry
          key={slug ?? index}
          title={title}
          tags={tags.split(', ')}
          body={body}
          links={{
            github: frontmatter?.github,
            submission: frontmatter?.submission,
            demo: frontmatter?.demo
          }} />))}
</>

export default Entries