module.exports = {
  siteMetadata: {
    title: `Dmitrijs Minajevs`,
    description: `Description?`,
    author: `@minajevs`,
  },
  plugins: [
    `gatsby-plugin-root-import`,
    `gatsby-plugin-sass`,
    {
      resolve: `gatsby-plugin-ts`,
      options: { codegen: true, fileName: `autogenerated/graphql-types.ts` },
    },
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images/`,
      },
    },
    `gatsby-plugin-mdx`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/src/data/`,
        ignore: [`**/\.*`], // ignore files starting with a dot
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Dmitrijs Minajevs`,
        short_name: `dexie.me`,
        start_url: `/`,
        background_color: `#ffffff`,
        theme_color: `#0c1937`,
        display: `minimal-ui`,
        icon: `src/images/icon.png`,
      },
    },
    `gatsby-plugin-offline`,
  ],
}
