import React from "react"
import { graphql, PageProps } from "gatsby"

import Layout from "../components/layout"
import { HackathonsPageQuery } from "autogenerated/graphql-types"
import Entries from "src/components/entries"

const HackathonsPage = ({ data }: PageProps<HackathonsPageQuery>) => (
  <Layout title="Hackathons">
    <Entries entries={data.allMdx.nodes} />
  </Layout>
)

export const query = graphql`
  query HackathonsPage {
    allMdx(
      filter: {frontmatter: {tags: {regex: "/.*hackathon.*/"}}},
      sort: {order: DESC, fields: frontmatter___date}) {
        nodes {
          ...Entry
        }
    }
  }
`

export default HackathonsPage
