import React from "react"
import { graphql, Link, PageProps } from "gatsby"

import Layout from "../components/layout"
import { PortfolioPageQuery } from "autogenerated/graphql-types"
import { foldNullables } from "src/utils/functional"
import { ret } from "src/utils/pointfree"
import Entry from "src/components/entry"

const PortfolioPage = ({ data }: PageProps<PortfolioPageQuery>) => {
  const { allMdx } = data
  const { nodes } = allMdx

  const entries = nodes.map(({ body, slug, frontmatter }, index) => foldNullables(
    { title: frontmatter?.title, tags: frontmatter?.tags },
    ret(null),
    ({ title, tags }) =>
      <Entry
        key={slug ?? index}
        title={title}
        tags={tags.split(', ')}
        body={body}
        links={{
          github: frontmatter?.github,
          submission: frontmatter?.submission,
          demo: frontmatter?.demo
        }} />
  ))

  return (
    <Layout title="Portfolio">
      {entries}
    </Layout>
  )
}

export const query = graphql`
  query PortfolioPage {
    allMdx(
      filter: {slug: {glob: "portfolio/*"}},
      sort: {order: DESC, fields: frontmatter___date}) {
        nodes {
          frontmatter {
            title
            tags
            github
            submission
            demo
          }
          body
          slug
        }
    }
  }
`

export default PortfolioPage
