import React from "react"
import { useStaticQuery, graphql } from "gatsby"
import Img, { FluidObject } from "gatsby-image"
import { pipe } from "fp-ts/lib/pipeable"
import * as O from 'fp-ts/lib/Option'
import { ImageQuery } from "autogenerated/graphql-types"

const query = graphql`
  query Image {
    placeholderImage: file(relativePath: { eq: "gatsby-icon.png" }) {
      childImageSharp {
        fluid(maxWidth: 300) {
          ...GatsbyImageSharpFluid
        }
      }
    }
  }
  `

const Image = () => {
  const data = useStaticQuery<ImageQuery>(query)

  return pipe(
    data?.placeholderImage?.childImageSharp?.fluid as FluidObject,
    O.fromNullable,
    O.fold(
      () => <div>Picture not found</div>,
      img => <Img fluid={img} />
    )
  )
}

export default Image
