import { SocialQuery } from 'autogenerated/graphql-types'
import { graphql, useStaticQuery } from 'gatsby'
import React, { useMemo } from 'react'
import { isNullOrUndefined, Nullable } from 'src/utils/predicates'
import { FaGithubSquare } from "@react-icons/all-files/fa/FaGithubSquare"
import { FaInstagramSquare } from "@react-icons/all-files/fa/FaInstagramSquare"
import { FaFacebookSquare } from "@react-icons/all-files/fa/FaFacebookSquare"
import { FaLinkedin } from "@react-icons/all-files/fa/FaLinkedin"
import { FaEnvelope } from "@react-icons/all-files/fa/FaEnvelope"

import styles from './social.module.scss'

const query = graphql`
  query Social {
    mdx(slug: {eq: "social"}) {
      frontmatter {
        github
		  	instagram
		  	facebook
		  	email
		  	linkedin
      }
    }
  }
`

type SocialLinks = 'github' | 'instagram' | 'facebook' | 'linkedin' | 'email'

const Icon: React.FC<{ href: Nullable<string> }> = ({ href, children }) =>
  isNullOrUndefined(href)
    ? null
    : (<a href={href}>{children}</a>)

const Icons = ({ github, instagram, facebook, linkedin, email }: Partial<Record<SocialLinks, Nullable<string>>>) => (<>
  <Icon href={github}>
    <FaGithubSquare />
  </Icon>
  <Icon href={instagram}>
    <FaInstagramSquare />
  </Icon>
  <Icon href={facebook}>
    <FaFacebookSquare />
  </Icon>
  <Icon href={linkedin}>
    <FaLinkedin />
  </Icon>
  <Icon href={`mailto:${email}`}>
    <FaEnvelope />
  </Icon>
</>)

export const Social = () => {
  const { mdx } = useStaticQuery<SocialQuery>(query)

  return (
    <div className={styles.social}>
      <Icons {...mdx?.frontmatter} />
    </div>
  )
}

export default Social